# Generated by Hype
require_relative 'domain.hddl'

# Predicates
SCOUT = [
  :scout
]
LOCATION = [
  :base,
  :forest,
  :mine
]
ON = 0
VISITED = 1
GATHERER = [
  :gatherer
]
ENEMY = [
  :enemy
]
RESOURCE = [
  :wood,
  :gold
]
EXIST = 2
EMPTY = 3
ATTACKER = [
  :attacker
]
HAVE = 4

Basic.problem(
  # Start
  [
    [
      [:gatherer, :base],
      [:scout, :base],
      [:attacker, :base]
    ],
    [],
    [
      # [:wood, :forest]
    ],
    [
      :gatherer
    ],
    [],
  ],
  # Tasks
  [
    [:grow, :gatherer, :scout, :attacker]
  ],
  # Debug
  ARGV[0] == 'debug'
)